# Generated by Django 4.0.4 on 2022-06-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TayfunBlog', '0005_category_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nameme',
            new_name='name',
        ),
    ]
