# Generated by Django 4.0.4 on 2022-06-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TayfunBlog', '0009_post_snippet_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.TextField(),
        ),
    ]
